let params = {
  camera: {
    viewAngle: 0.8,
    Default: { fov: 60, near: 1, far: 300 },
    Near: { fov: 60, near: 1, far: 200 },
    Overhead: { fov: 60, near: 1, far: 4000 },
    Map: { fov: 70, near: 1, far: 4000 },
    CameraView: { fov: 30.5, near: 1, far: 1500 },
    Orthographic: { fov: 70, near: 1, far: 4000 },
    laneWidth: 4.5,
    laneWidthToViewDistanceRatio: 5,
  },
  ground: {
    defaults: {
      mpp: 0.125,
      xres: 8192,
      yres: 8192,
      xorigin: 4096,
      yorigin: 4096,
      type: "default",
      tileRange: 4,
    },
    sunnyvale_big_loop: {
      mpp: 0.125,
      xres: 24576,
      yres: 16384,
      xorigin: 587392,
      yorigin: 4140800,
      type: "default",
      tileRange: 4,
    },
  },
  planning: {
    minInterval: 0.1,
    defaults: { width: 1.4 },
    pathProperties: {
      default: { width: 0.1, color: 6385381, opacity: 1, zOffset: 1.4 },
      trajectory: { width: 0.2, color: 255, opacity: 0.7, zOffset: 2 },
      planning_reference_line_0: {
        width: 1.2,
        color: 7905226,
        opacity: 0.3,
        zOffset: 1.1,
      },
      planning_reference_line_1: {
        width: 1.2,
        color: 10328987,
        opacity: 0.3,
        zOffset: 1.1,
      },
      planning_reference_line_2: {
        width: 1.2,
        color: 10328987,
        opacity: 0.3,
        zOffset: 1.1,
      },
      planning_reference_line_3: {
        width: 1.2,
        color: 10328987,
        opacity: 0.3,
        zOffset: 1.1,
      },
      planning_reference_line_4: {
        width: 1.2,
        color: 10328987,
        opacity: 0.3,
        zOffset: 1.1,
      },
      planning_reference_line_5: {
        width: 1.2,
        color: 10328987,
        opacity: 0.3,
        zOffset: 1.1,
      },
      left_reference_line_gap: {
        width: 1.2,
        color: 12040102,
        opacity: 0.3,
        zOffset: 1.2,
      },
      right_reference_line_gap: {
        width: 1.2,
        color: 12040102,
        opacity: 0.3,
        zOffset: 1.2,
      },
      DpPolyPathOptimizer: {
        width: 0.4,
        color: 9305268,
        opacity: 0.8,
        zOffset: 1.2,
      },
      PIECEWISE_JERK_PATH_OPTIMIZER: {
        width: 0.2,
        color: 3580651,
        opacity: 1,
        zOffset: 1.3,
      },
      planning_path_boundary_1: {
        style: "dash",
        width: 0.1,
        color: 15793920,
        opacity: 1,
        zOffset: 1.3,
      },
      planning_path_boundary_2: {
        style: "dash",
        width: 0.1,
        color: 15793920,
        opacity: 1,
        zOffset: 1.3,
      },
      "Planning PathData": {
        width: 1.2,
        color: 4365204,
        opacity: 0.4,
        zOffset: 1.8,
      },
      ILQR_PATH_OPTIMIZER: {
        width: 0.9,
        color: 4365204,
        opacity: 0.6,
        zOffset: 1.8,
      },
    },
  },
  options: {
    showTasks: { default: true },
    showModuleController: { default: false },
    showMenu: { default: false },
    showRouteEditingBar: { default: false },
    showPOI: { default: false },
    showDataRecorder: { default: false },
    showProfile: { default: false },
    showPNCMonitor: { default: false },
    showPredictionMonitor: { default: false },
    showEfficientLaneMonitor: { default: false },
    showVirtualCloseLoop: { default: false },
    showCloseLoop: { default: false },
    showDataCollectionMonitor: { default: false },
    showFuelClient: { default: false },
    enableSimControl: { default: false },
    lockTaskPanel: { default: false },
    showVideo: { default: true },
    showVideo2: { default: true },
    showVideo3: { default: false },
    showVideo4: { default: false },
    showVideo5: { default: false },
    showVideo6: { default: false },
    showVideo7: { default: false },
    showModuleDelay: { default: false },
    showSimpleMonitor: { default: false },
    showMessageSize: { default: false },
    showSpeedAcc: { default: true },
    showDeltaTime: { default: true },
    showTimeInterval: { default: false },
    showControlPanel: { default: true },
    showBevRight: { default: true },
    showPredictionObject: { default: true },
    showPerceptionObject: { default: false },
    showPncObject: { default: false },
    showPolygon: { default: false },
    showFollowCar: { default: true },
    showHighMap: { default: true },
    showMapShoulder: { default: true },
    showTopoTree: { default: false },
    showRoadStructure: { default: false },
    showVectorizedLane: { default: false },
    showLaneMap: { default: false },
    showPredictionPath: { default: false },
    showCurbSet: { default: false },
    showNaviTwoKm: { default: false },
    showDimensionalCar: { default: false },
    showConsoleTeleopMonitor: { default: false },
    showCarTeleopMonitor: { default: false },
    cameraAngle: { default: "Orthographic", hasCameraView: false },
    showDecisionMain: { default: true, menuId: "decisionMain" },
    showDecisionObstacle: { default: true, menuId: "decisionObstacle" },
    showPlanningTrajectory: { default: true, menuId: "planningTrajectory" },
    showPlanningCar: { default: false, menuId: "planningCar" },
    showPlanningPath: { default: true, menuId: "planningPath" },
    showPlanningRSSInfo: { default: false, menuId: "rssInfo" },
    showPlanningMultiPolicy: { default: false, menuId: "multiPolicy" },
    showRouting: { default: false, menuId: "routing" },
    showPredictionMajor: { default: true, menuId: "predictionMajor" },
    showVehicleFlowLines: { default: false, menuId: "vehicleFlowLines" },
    showEfficientLane: { default: false, menuId: "efficientLane" },
    showEfficientNavi: { default: true, menuId: "efficientNavi" },
    showCurbTag: { default: true, menuId: "curbTag" },
    showRoadStructureCurb: { default: false, menuId: "roadStructureCurb" },
    showPredictionMinor: { default: true, menuId: "predictionMinor" },
    showGaussianInfo: { default: false, menuId: "predictionGaussianInfo" },
    showPredictionPriority: { default: false, menuId: "predictionPriority" },
    showPredictionInteractiveTag: {
      default: false,
      menuId: "predictionInteractiveTag",
    },
    showPredictionDecision: { default: true, menuId: "predictionDecision" },
    showPointCloud: { default: false, menuId: "perceptionPointCloud" },
    showPerceptionObjectTopic: {
      default: false,
      menuId: "perceptionObjectTopic",
    },
    showPerceptionTypeStaticUnkonwn: {
      default: false,
      menuId: "perceptionTypeStaticUnkonwn",
    },
    showPerceptionLaneMarker: {
      default: false,
      menuId: "perceptionLaneMarker",
    },
    showObstacleStatus: { default: false, menuId: "obstacleStatus" },
    showGoalLaneInJunction: { default: true, menuId: "goalLaneInJunction" },
    showAdcLocalizationQuality: {
      default: false,
      menuId: "localizationQuality",
    },
    showObstaclesVehicle: { default: true, menuId: "perceptionVehicle" },
    showObstaclesPedestrian: { default: true, menuId: "perceptionPedestrian" },
    showObstaclesBicycle: { default: true, menuId: "perceptionBicycle" },
    showObstaclesUnknownMovable: {
      default: true,
      menuId: "perceptionUnknownMovable",
    },
    showObstaclesUnknownUnmovable: {
      default: true,
      menuId: "perceptionUnknownUnmovable",
    },
    showObstaclesUnknown: { default: true, menuId: "perceptionUnknown" },
    showObstaclesVirtual: { default: false, menuId: "perceptionVirtual" },
    showObstaclesCipv: { default: true, menuId: "perceptionCipv" },
    showObstaclesVelocity: { default: true, menuId: "perceptionVelocity" },
    showObstaclesHeading: { default: true, menuId: "perceptionHeading" },
    showObstaclesId: { default: true, menuId: "perceptionId" },
    showObstaclesInfo: { default: true, menuId: "perceptionObstacleInfo" },
    showObstaclesLidarSensor: {
      default: false,
      menuId: "perceptionLidarSensor",
    },
    showObstaclesRadarSensor: {
      default: false,
      menuId: "perceptionRadarSensor",
    },
    showObstaclesCameraSensor: {
      default: false,
      menuId: "perceptionCameraSensor",
    },
    showObstaclesV2xInfo: { default: false, menuId: "perceptionV2xInfo" },
    showObstaclesPostFusionObject: {
      default: true,
      menuId: "showObstaclesPostFusionObject",
    },
    showObstaclesBevObject: {
      default: false,
      menuId: "showObstaclesBevObject",
    },
    showObstaclesPvFmNarrowObject: {
      default: false,
      menuId: "showObstaclesPvFmNarrowObject",
    },
    showObstaclesPvFmWideObject: {
      default: false,
      menuId: "showObstaclesPvFmWideObject",
    },
    showObstaclesPvLbPinholeObject: {
      default: false,
      menuId: "showObstaclesPvLbPinholeObject",
    },
    showObstaclesPvRbPinholeObject: {
      default: false,
      menuId: "showObstaclesPvRbPinholeObject",
    },
    showObstaclesPvFmFisheyeObject: {
      default: false,
      menuId: "showObstaclesPvFmFisheyeObject",
    },
    showObstaclesPvLmFisheyeObject: {
      default: false,
      menuId: "showObstaclesPvLmFisheyeObject",
    },
    showObstaclesPvRmFisheyeObject: {
      default: false,
      menuId: "showObstaclesPvRmFisheyeObject",
    },
    showObstaclesPvBmFisheyeObject: {
      default: false,
      menuId: "showObstaclesPvBmFisheyeObject",
    },
    showObstaclesBevPostObject: {
      default: false,
      menuId: "showObstaclesBevPostObject",
    },
    showObstaclesPvPostFmNarrowObject: {
      default: false,
      menuId: "showObstaclesPvPostFmNarrowObject",
    },
    showObstaclesPvPostFmWideObject: {
      default: false,
      menuId: "showObstaclesPvPostFmWideObject",
    },
    showObstaclesPvPostLbPinholeObject: {
      default: false,
      menuId: "showObstaclesPvPostLbPinholeObject",
    },
    showObstaclesPvPostRbPinholeObject: {
      default: false,
      menuId: "showObstaclesPvPostRbPinholeObject",
    },
    showObstaclesOccupancyObject: {
      default: false,
      menuId: "showObstaclesOccupancyObject",
    },
    showPositionGps: { default: false, menuId: "positionGps" },
    showPositionLocalization: { default: true, menuId: "positionLocalization" },
    showVirtualChassis: { default: false, menuId: "virtualChassis" },
    showPositionCloseLoop: { default: true, menuId: "positionCloseLoop" },
    showPositionShadow: { default: false, menuId: "positionShadow" },
    showMapCrosswalk: { default: true, menuId: "mapCrosswalk" },
    showMapClearArea: { default: true, menuId: "mapClearArea" },
    showMapJunction: { default: false, menuId: "mapJunction" },
    showMapPncJunction: { default: false, menuId: "mapPncJunction" },
    showMapLane: { default: true, menuId: "mapLane" },
    showMapCenterLane: { default: false, menuId: "mapCenterLane" },
    showMapRoad: { default: false, menuId: "mapRoad" },
    showMapSignal: { default: true, menuId: "mapSignal" },
    showMapStopSign: { default: true, menuId: "mapStopSign" },
    showMapYield: { default: true, menuId: "mapYield" },
    showMapSpeedBump: { default: true, menuId: "mapSpeedBump" },
    showMapParkingSpace: { default: true, menuId: "mapParkingSpace" },
    showMapLaneId: { default: false, menuId: "mapLaneId" },
    showDefaultRoutingInput: { default: false },
    showCycleNumberInput: { default: false },
    selectPNCMonitorTab: { default: 0 },
    showPNCPlanningPanel: { default: false },
    showPNCPlanningCore: { default: true },
    showPNCPlanningBoundary: { default: true },
    showPNCPlanningBuffer: { default: false },
    showPNCControlPanel: { default: false },
    showPlanningStatusPanel: { default: true },
    showOperator: { default: false },
    showSideBar: { default: false },
    showTools: { default: false },
    showTimestamp: { default: true },
    cameraDraggable: { default: false },
    showPncDebug: { default: false },
    showLonBehavior: { default: false },
    showSpeedHeuristic: { default: true },
    showPlanningSTGraph: { default: true },
    showPlanningVTGraph: { default: true },
    showPlanningSpeed: { default: true },
    showPlanningAcceleration: { default: true },
    showPlanningTheta: { default: true },
    showPlanningKappa: { default: true },
    showPlanningKappaDerivative: { default: true },
    showReferenceLineTheta: { default: true },
    showReferenceLineKappa: { default: true },
    showReferenceLineKappaDerivative: { default: true },
    showControlTrajectory: { default: true },
    showControlSpeed: { default: true },
    showControlAcceleration: { default: true },
    showControlCurvature: { default: true },
    showControlStationError: { default: true },
    showControlLateralError: { default: true },
    showControlHeadingError: { default: true },
    showLatencyGraph: { default: true },
    showInteractColor: { default: false },
  },
  routingEditor: { radiusOfMapRequest: 2000 },
  navigation: {
    map: "BaiduMap",
    mapAPiUrl:
      "https://api.map.baidu.com/api?v=3.0&ak=0kKZnWWhXEPfzIkklmzAa3dZ&callback=initMap",
  },
  debug: { autoMonitorMessage: false, performanceMonitor: false },
  server: { port: 8888 },
};

module.exports = params