let store = {
  timestamp: 0,
  isInitialized: true,
  studioConnector: {
    scenarioSet: [],
    currentScenarioSetId: "none",
    currentScenarioId: "none",
    remoteScenarioSetList: [],
    certificateStatus: "normal",
    typeConditionValue: "All",
    statusConditionValue: "All",
    remoteDynamicModelList: [],
    remoteRecordList: [],
    vehicleUpdateStatus: 0,
    vehicleInfoList: [],
  },
  hmi: {
    modes: [],
    vehicles: [],
    defaultVehicleSize: { height: 1.48, width: 2.11, length: 4.933 },
    vehicleParam: {
      frontEdgeToCenter: 3.89,
      backEdgeToCenter: 1.043,
      leftEdgeToCenter: 1.055,
      rightEdgeToCenter: 1.055,
      height: 1.48,
      width: 2.11,
      length: 4.933,
      steerRatio: 16,
      wheelBase: 2.8448,
    },
    maps: [],
    displayName: {},
    utmZoneId: 10,
    currentMode: "none",
    currTimeS: 0,
    totalTimeS: 0,
    playRecordStatus: "CLOSED",
    currentRecordId: "",
    rate: 1,
    isMainConnected: false,
    currentVehicle: "none",
    currentMap: "none",
    moduleStatus: {},
    componentStatus: {},
    otherComponentStatus: {},
    enableStartAuto: false,
    dockerImage: "unknown",
    isCoDriver: false,
    isMute: false,
    isPreprocess: false,
    isVehicleCalibrationMode: false,
    isSensorCalibrationMode: false,
    dataCollectionUpdateStatus: {},
    dataCollectionProgress: {},
    lidars: {},
    camera: {},
    mainSensor: "none",
    updateConfiguration: false,
    preprocessStarted: false,
    preprocessFinished: false,
    unexpectedAborted: false,
    preprocessStatus: "UNKNOWN",
    logString: "",
    preprocessProgress: 0,
    preprocessMonitorItemTimeStamp: null,
    counter: 0,
    dynamicModels: [],
    currentDynamicModel: "",
    records: {},
    currentVehicleType: 0,
    currentCameraSensorChannel: "",
    currentPointCloudChannel: "",
    currentPointCloudColor: "0",
  },
  planningData: {
    data: {
      slGraph: {},
      stGraph: {},
      stSpeedGraph: {},
      speedGraph: {},
      accelerationGraph: {},
      thetaGraph: {},
      kappaGraph: {},
      dkappaGraph: {},
    },
    chartData: [],
    scenarioHistory: [],
    planningTimeSec: null,
    planningObstacleId: null,
  },
  planningStatus: {
    trajectoryType: "",
    replanReason: [],
    laneChangeFsmStatus: [],
    expectationSpeed: "",
    latErrorToLaneCenter: "",
    pncDebug: "",
    lonBehavior: "",
    planningMode: "",
  },
  autoDrivingCar: { autoDrivingCar: "" },
  virtualCar: { virtualCar: "" },
  controlData: {
    data: {
      trajectoryGraph: {
        plan: [],
        target: [],
        real: [],
        autoModeZone: [],
        steerCurve: [],
        currentTargetPoint: [],
      },
      pose: { x: null, y: null, heading: null },
      speedGraph: { plan: [], target: [], real: [], autoModeZone: [] },
      curvatureGraph: { plan: [], target: [], real: [], autoModeZone: [] },
      accelerationGraph: { plan: [], target: [], real: [], autoModeZone: [] },
      stationErrorGraph: { error: [] },
      headingErrorGraph: { error: [] },
      lateralErrorGraph: { error: [] },
      realSpeedGraph: { plan: [], target: [], real: [], autoModeZone: [] },
      realAccelerationGraph: {
        plan: [],
        target: [],
        real: [],
        autoModeZone: [],
      },
      realAngleGraph: { plan: [], target: [], real: [], autoModeZone: [] },
    },
    lastUpdatedTime: null,
  },
  latency: { data: {}, lastUpdatedTime: 0 },
  trafficSignal: { color: "" },
  meters: {
    throttlePercent: 0,
    brakePercent: 0,
    acceleration: 0,
    speed: 0,
    steeringAngle: 0,
    steeringAngleRad: 0,
    steeringPercentage: 0,
    leftTurnSignal: false,
    rightTurnSignal: false,
    batteryPercentage: null,
    gearLocation: "",
    drivingMode: "UNKNOWN",
    newDrivingMode: "UNKNOWN",
    chassisDrivingMode: "UNKNOWN",
    disengageType: "UNKNOWN",
    isAutoMode: false,
    isNewAutoMode: false,
    turnSignal: "",
    drivingAction: "",
    trafficLightSign: null,
    timestampSec: "",
    version: "",
    locQuality: "",
    rtkStatus: "",
    expectationSpeed: "",
    humanLanePreference: "",
    realtimeMessageSize: 60013,
    realtimeStamp: 1722311618743,
    mapMessageSize: 0,
    objectNew: null,
    predictionObstacle: null,
    predictionObstacleId: null,
    effLaneIndex: null,
    selectEfficientLaneSequence: null,
    efficientLaneSequenceMaxIndex: null,
    effLaneMaxSelect: false,
    postTbtInfos: null,
    deltaTime1: null,
    deltaTime2: null,
    deltaTime1_point_cloud: { pcd: "" },
    deltaTime2_point_cloud: { pcd: "" },
    cyberTimestamp: null,
    timestampTimeDiff: null,
    enterObstacleId: null,
    useHdmap: "",
    mapMode: "",
    mapFile: "",
    steeringTorqueNm: 0,
    laneLightSet: [],
    curBin: 0,
  },
  monitor: {
    lastUpdateTimestamp: 0,
    refreshTimer: null,
    hasActiveNotification: false,
    items: [],
    rssInfo: [],
    isSirenOn: false,
  },
  options: {
    cameraAngleNames: null,
    mainSideBarOptions: [
      "showTasks",
      "showModuleController",
      "showMenu",
      "showRouteEditingBar",
      "showDataRecorder",
      "showProfile",
    ],
    secondarySideBarOptions: ["showPOI"],
    menuIdOptionMapping: {
      decisionMain: "showDecisionMain",
      decisionObstacle: "showDecisionObstacle",
      planningTrajectory: "showPlanningTrajectory",
      planningCar: "showPlanningCar",
      planningPath: "showPlanningPath",
      rssInfo: "showPlanningRSSInfo",
      multiPolicy: "showPlanningMultiPolicy",
      routing: "showRouting",
      predictionMajor: "showPredictionMajor",
      vehicleFlowLines: "showVehicleFlowLines",
      efficientLane: "showEfficientLane",
      efficientNavi: "showEfficientNavi",
      curbTag: "showCurbTag",
      roadStructureCurb: "showRoadStructureCurb",
      predictionMinor: "showPredictionMinor",
      predictionGaussianInfo: "showGaussianInfo",
      predictionPriority: "showPredictionPriority",
      predictionInteractiveTag: "showPredictionInteractiveTag",
      predictionDecision: "showPredictionDecision",
      perceptionPointCloud: "showPointCloud",
      perceptionObjectTopic: "showPerceptionObjectTopic",
      perceptionTypeStaticUnkonwn: "showPerceptionTypeStaticUnkonwn",
      perceptionLaneMarker: "showPerceptionLaneMarker",
      obstacleStatus: "showObstacleStatus",
      goalLaneInJunction: "showGoalLaneInJunction",
      localizationQuality: "showAdcLocalizationQuality",
      perceptionVehicle: "showObstaclesVehicle",
      perceptionPedestrian: "showObstaclesPedestrian",
      perceptionBicycle: "showObstaclesBicycle",
      perceptionUnknownMovable: "showObstaclesUnknownMovable",
      perceptionUnknownUnmovable: "showObstaclesUnknownUnmovable",
      perceptionUnknown: "showObstaclesUnknown",
      perceptionVirtual: "showObstaclesVirtual",
      perceptionCipv: "showObstaclesCipv",
      perceptionVelocity: "showObstaclesVelocity",
      perceptionHeading: "showObstaclesHeading",
      perceptionId: "showObstaclesId",
      perceptionObstacleInfo: "showObstaclesInfo",
      perceptionLidarSensor: "showObstaclesLidarSensor",
      perceptionRadarSensor: "showObstaclesRadarSensor",
      perceptionCameraSensor: "showObstaclesCameraSensor",
      perceptionV2xInfo: "showObstaclesV2xInfo",
      showObstaclesPostFusionObject: "showObstaclesPostFusionObject",
      showObstaclesBevObject: "showObstaclesBevObject",
      showObstaclesPvFmNarrowObject: "showObstaclesPvFmNarrowObject",
      showObstaclesPvFmWideObject: "showObstaclesPvFmWideObject",
      showObstaclesPvLbPinholeObject: "showObstaclesPvLbPinholeObject",
      showObstaclesPvRbPinholeObject: "showObstaclesPvRbPinholeObject",
      showObstaclesPvFmFisheyeObject: "showObstaclesPvFmFisheyeObject",
      showObstaclesPvLmFisheyeObject: "showObstaclesPvLmFisheyeObject",
      showObstaclesPvRmFisheyeObject: "showObstaclesPvRmFisheyeObject",
      showObstaclesPvBmFisheyeObject: "showObstaclesPvBmFisheyeObject",
      showObstaclesBevPostObject: "showObstaclesBevPostObject",
      showObstaclesPvPostFmNarrowObject: "showObstaclesPvPostFmNarrowObject",
      showObstaclesPvPostFmWideObject: "showObstaclesPvPostFmWideObject",
      showObstaclesPvPostLbPinholeObject: "showObstaclesPvPostLbPinholeObject",
      showObstaclesPvPostRbPinholeObject: "showObstaclesPvPostRbPinholeObject",
      showObstaclesOccupancyObject: "showObstaclesOccupancyObject",
      positionGps: "showPositionGps",
      positionLocalization: "showPositionLocalization",
      virtualChassis: "showVirtualChassis",
      positionCloseLoop: "showPositionCloseLoop",
      positionShadow: "showPositionShadow",
      mapCrosswalk: "showMapCrosswalk",
      mapClearArea: "showMapClearArea",
      mapJunction: "showMapJunction",
      mapPncJunction: "showMapPncJunction",
      mapLane: "showMapLane",
      mapCenterLane: "showMapCenterLane",
      mapRoad: "showMapRoad",
      mapSignal: "showMapSignal",
      mapStopSign: "showMapStopSign",
      mapYield: "showMapYield",
      mapSpeedBump: "showMapSpeedBump",
      mapParkingSpace: "showMapParkingSpace",
      mapLaneId: "showMapLaneId",
    },
    customizedToggles: {},
    showTasks: true,
    showModuleController: false,
    showMenu: false,
    showRouteEditingBar: false,
    showPOI: false,
    showDataRecorder: false,
    showProfile: false,
    showPNCMonitor: false,
    showPredictionMonitor: false,
    showEfficientLaneMonitor: false,
    showVirtualCloseLoop: false,
    showCloseLoop: false,
    showDataCollectionMonitor: false,
    showFuelClient: false,
    enableSimControl: false,
    lockTaskPanel: false,
    showVideo: true,
    showVideo2: true,
    showVideo3: false,
    showVideo4: false,
    showVideo5: false,
    showVideo6: false,
    showVideo7: false,
    showModuleDelay: false,
    showSimpleMonitor: false,
    showMessageSize: false,
    showSpeedAcc: true,
    showDeltaTime: true,
    showTimeInterval: false,
    showControlPanel: true,
    showBevRight: true,
    showPredictionObject: true,
    showPerceptionObject: false,
    showPncObject: false,
    showPolygon: false,
    showFollowCar: true,
    showHighMap: true,
    showMapShoulder: true,
    showTopoTree: false,
    showRoadStructure: true,
    showVectorizedLane: false,
    showLaneMap: false,
    showPredictionPath: false,
    showCurbSet: false,
    showNaviTwoKm: false,
    showDimensionalCar: false,
    showConsoleTeleopMonitor: false,
    showCarTeleopMonitor: false,
    cameraAngle: "Orthographic",
    showDecisionMain: true,
    showDecisionObstacle: true,
    showPlanningTrajectory: true,
    showPlanningCar: false,
    showPlanningPath: true,
    showPlanningRSSInfo: false,
    showPlanningMultiPolicy: false,
    showRouting: false,
    showPredictionMajor: true,
    showVehicleFlowLines: false,
    showEfficientLane: false,
    showEfficientNavi: true,
    showCurbTag: true,
    showRoadStructureCurb: false,
    showPredictionMinor: true,
    showGaussianInfo: false,
    showPredictionPriority: false,
    showPredictionInteractiveTag: false,
    showPredictionDecision: true,
    showPointCloud: false,
    showPerceptionObjectTopic: false,
    showPerceptionTypeStaticUnkonwn: false,
    showPerceptionLaneMarker: false,
    showObstacleStatus: false,
    showGoalLaneInJunction: true,
    showAdcLocalizationQuality: false,
    showObstaclesVehicle: true,
    showObstaclesPedestrian: true,
    showObstaclesBicycle: true,
    showObstaclesUnknownMovable: true,
    showObstaclesUnknownUnmovable: true,
    showObstaclesUnknown: true,
    showObstaclesVirtual: false,
    showObstaclesCipv: true,
    showObstaclesVelocity: true,
    showObstaclesHeading: true,
    showObstaclesId: true,
    showObstaclesInfo: true,
    showObstaclesLidarSensor: false,
    showObstaclesRadarSensor: false,
    showObstaclesCameraSensor: false,
    showObstaclesV2xInfo: false,
    showObstaclesPostFusionObject: true,
    showObstaclesBevObject: false,
    showObstaclesPvFmNarrowObject: false,
    showObstaclesPvFmWideObject: false,
    showObstaclesPvLbPinholeObject: false,
    showObstaclesPvRbPinholeObject: false,
    showObstaclesPvFmFisheyeObject: false,
    showObstaclesPvLmFisheyeObject: false,
    showObstaclesPvRmFisheyeObject: false,
    showObstaclesPvBmFisheyeObject: false,
    showObstaclesBevPostObject: false,
    showObstaclesPvPostFmNarrowObject: false,
    showObstaclesPvPostFmWideObject: false,
    showObstaclesPvPostLbPinholeObject: false,
    showObstaclesPvPostRbPinholeObject: false,
    showObstaclesOccupancyObject: false,
    showPositionGps: false,
    showPositionLocalization: true,
    showVirtualChassis: false,
    showPositionCloseLoop: true,
    showPositionShadow: false,
    showMapCrosswalk: true,
    showMapClearArea: true,
    showMapJunction: false,
    showMapPncJunction: false,
    showMapLane: true,
    showMapCenterLane: false,
    showMapRoad: false,
    showMapSignal: true,
    showMapStopSign: true,
    showMapYield: true,
    showMapSpeedBump: true,
    showMapParkingSpace: true,
    showMapLaneId: false,
    showDefaultRoutingInput: false,
    showCycleNumberInput: false,
    selectPNCMonitorTab: 0,
    showPNCPlanningPanel: false,
    showPNCPlanningCore: true,
    showPNCPlanningBoundary: true,
    showPNCPlanningBuffer: false,
    showPNCControlPanel: false,
    showPlanningStatusPanel: true,
    showOperator: false,
    showSideBar: false,
    showTools: false,
    showTimestamp: true,
    cameraDraggable: false,
    showPncDebug: false,
    showLonBehavior: false,
    showSpeedHeuristic: true,
    showPlanningSTGraph: true,
    showPlanningVTGraph: true,
    showPlanningSpeed: true,
    showPlanningAcceleration: true,
    showPlanningTheta: true,
    showPlanningKappa: true,
    showPlanningKappaDerivative: true,
    showReferenceLineTheta: true,
    showReferenceLineKappa: true,
    showReferenceLineKappaDerivative: true,
    showControlTrajectory: true,
    showControlSpeed: true,
    showControlAcceleration: true,
    showControlCurvature: true,
    showControlStationError: true,
    showControlLateralError: true,
    showControlHeadingError: true,
    showLatencyGraph: true,
    showInteractColor: false,
    togglesToHide: {
      perceptionPointCloud: false,
      perceptionLaneMarker: false,
      planningCar: false,
    },
  },
  routeEditingManager: {
    defaultParkingInfo: {},
    currentDefaultRouting: "none",
    parkingRoutingDistanceThreshold: 20,
    defaultRoutingEndPoint: {},
    defaultRoutings: {},
    defaultRoutingDistanceThreshold: 10,
    currentPOI: "none",
    inDefaultRoutingMode: false,
  },
  geolocation: {},
  moduleDelay: {},
  cameraData: {
    initPosition: { x: 0, y: 0, z: 0 },
    deltaPosition: { x: 0, y: 0, z: 0 },
    initStaticRotation: { x: 0, y: 0, z: 0 },
    deltaStaticRotation: { x: 0, y: 0, z: 0 },
    initDynamicRotation: { x: 0, y: 0, z: 0 },
    deltaDynamicRotation: { x: 0, y: 0, z: 0 },
    cameraChannels: [],
    imageSrcData: null,
    imageTimestamp: null,
    deltaT1: null,
    deltaT2: null,
    imageAspectRatio: null,
  },
  cameraData2: {
    initPosition: { x: 0, y: 0, z: 0 },
    deltaPosition: { x: 0, y: 0, z: 0 },
    initStaticRotation: { x: 0, y: 0, z: 0 },
    deltaStaticRotation: { x: 0, y: 0, z: 0 },
    initDynamicRotation: { x: 0, y: 0, z: 0 },
    deltaDynamicRotation: { x: 0, y: 0, z: 0 },
    cameraChannels: [],
    imageSrcData: null,
    imageTimestamp: null,
    deltaT1: null,
    deltaT2: null,
    imageAspectRatio: null,
    defaultChannel: "/camera_lb_pinhole/image_color/compressed",
  },
  cameraData3: {
    initPosition: { x: 0, y: 0, z: 0 },
    deltaPosition: { x: 0, y: 0, z: 0 },
    initStaticRotation: { x: 0, y: 0, z: 0 },
    deltaStaticRotation: { x: 0, y: 0, z: 0 },
    initDynamicRotation: { x: 0, y: 0, z: 0 },
    deltaDynamicRotation: { x: 0, y: 0, z: 0 },
    cameraChannels: [],
    imageSrcData: null,
    imageTimestamp: null,
    deltaT1: null,
    deltaT2: null,
    imageAspectRatio: null,
  },
  cameraData4: {
    initPosition: { x: 0, y: 0, z: 0 },
    deltaPosition: { x: 0, y: 0, z: 0 },
    initStaticRotation: { x: 0, y: 0, z: 0 },
    deltaStaticRotation: { x: 0, y: 0, z: 0 },
    initDynamicRotation: { x: 0, y: 0, z: 0 },
    deltaDynamicRotation: { x: 0, y: 0, z: 0 },
    cameraChannels: [],
    imageSrcData: null,
    imageTimestamp: null,
    deltaT1: null,
    deltaT2: null,
    imageAspectRatio: null,
  },
  cameraData5: {
    initPosition: { x: 0, y: 0, z: 0 },
    deltaPosition: { x: 0, y: 0, z: 0 },
    initStaticRotation: { x: 0, y: 0, z: 0 },
    deltaStaticRotation: { x: 0, y: 0, z: 0 },
    initDynamicRotation: { x: 0, y: 0, z: 0 },
    deltaDynamicRotation: { x: 0, y: 0, z: 0 },
    cameraChannels: [],
    imageSrcData: null,
    imageTimestamp: null,
    deltaT1: null,
    deltaT2: null,
    imageAspectRatio: null,
  },
  cameraData6: {
    initPosition: { x: 0, y: 0, z: 0 },
    deltaPosition: { x: 0, y: 0, z: 0 },
    initStaticRotation: { x: 0, y: 0, z: 0 },
    deltaStaticRotation: { x: 0, y: 0, z: 0 },
    initDynamicRotation: { x: 0, y: 0, z: 0 },
    deltaDynamicRotation: { x: 0, y: 0, z: 0 },
    cameraChannels: [],
    imageSrcData: null,
    imageTimestamp: null,
    deltaT1: null,
    deltaT2: null,
    imageAspectRatio: null,
  },
  cameraData7: {
    initPosition: { x: 0, y: 0, z: 0 },
    deltaPosition: { x: 0, y: 0, z: 0 },
    initStaticRotation: { x: 0, y: 0, z: 0 },
    deltaStaticRotation: { x: 0, y: 0, z: 0 },
    initDynamicRotation: { x: 0, y: 0, z: 0 },
    deltaDynamicRotation: { x: 0, y: 0, z: 0 },
    cameraChannels: [],
    imageSrcData: null,
    imageTimestamp: null,
    deltaT1: null,
    deltaT2: null,
    imageAspectRatio: null,
  },
  storyTellers: { stories: {} },
  teleop: {
    audioEnabled: false,
    micEnabled: false,
    videoEnabled: false,
    modemInfo: {},
  },
  dimension: {
    hmi: {
      modes: [],
      vehicles: [],
      defaultVehicleSize: { height: 1.48, width: 2.11, length: 4.933 },
      vehicleParam: {
        frontEdgeToCenter: 3.89,
        backEdgeToCenter: 1.043,
        leftEdgeToCenter: 1.055,
        rightEdgeToCenter: 1.055,
        height: 1.48,
        width: 2.11,
        length: 4.933,
        steerRatio: 16,
        wheelBase: 2.8448,
      },
      maps: [],
      displayName: {},
      utmZoneId: 10,
      currentMode: "none",
      currTimeS: 0,
      totalTimeS: 0,
      playRecordStatus: "CLOSED",
      currentRecordId: "",
      rate: 1,
      isMainConnected: false,
      currentVehicle: "none",
      currentMap: "none",
      moduleStatus: {},
      componentStatus: {},
      otherComponentStatus: {},
      enableStartAuto: false,
      dockerImage: "unknown",
      isCoDriver: false,
      isMute: false,
      isPreprocess: false,
      isVehicleCalibrationMode: false,
      isSensorCalibrationMode: false,
      dataCollectionUpdateStatus: {},
      dataCollectionProgress: {},
      lidars: {},
      camera: {},
      mainSensor: "none",
      updateConfiguration: false,
      preprocessStarted: false,
      preprocessFinished: false,
      unexpectedAborted: false,
      preprocessStatus: "UNKNOWN",
      logString: "",
      preprocessProgress: 0,
      preprocessMonitorItemTimeStamp: null,
      counter: 0,
      dynamicModels: [],
      currentDynamicModel: "",
      records: {},
      currentVehicleType: 0,
      currentCameraSensorChannel: "",
      currentPointCloudChannel: "",
      currentPointCloudColor: "0",
    },
    options: {
      cameraAngleNames: null,
      mainSideBarOptions: [
        "showTasks",
        "showModuleController",
        "showMenu",
        "showRouteEditingBar",
        "showDataRecorder",
        "showProfile",
      ],
      secondarySideBarOptions: ["showPOI"],
      menuIdOptionMapping: {
        decisionMain: "showDecisionMain",
        decisionObstacle: "showDecisionObstacle",
        planningTrajectory: "showPlanningTrajectory",
        planningCar: "showPlanningCar",
        planningPath: "showPlanningPath",
        rssInfo: "showPlanningRSSInfo",
        multiPolicy: "showPlanningMultiPolicy",
        routing: "showRouting",
        predictionMajor: "showPredictionMajor",
        vehicleFlowLines: "showVehicleFlowLines",
        efficientLane: "showEfficientLane",
        efficientNavi: "showEfficientNavi",
        curbTag: "showCurbTag",
        roadStructureCurb: "showRoadStructureCurb",
        predictionMinor: "showPredictionMinor",
        predictionGaussianInfo: "showGaussianInfo",
        predictionPriority: "showPredictionPriority",
        predictionInteractiveTag: "showPredictionInteractiveTag",
        predictionDecision: "showPredictionDecision",
        perceptionPointCloud: "showPointCloud",
        perceptionObjectTopic: "showPerceptionObjectTopic",
        perceptionTypeStaticUnkonwn: "showPerceptionTypeStaticUnkonwn",
        perceptionLaneMarker: "showPerceptionLaneMarker",
        obstacleStatus: "showObstacleStatus",
        goalLaneInJunction: "showGoalLaneInJunction",
        localizationQuality: "showAdcLocalizationQuality",
        perceptionVehicle: "showObstaclesVehicle",
        perceptionPedestrian: "showObstaclesPedestrian",
        perceptionBicycle: "showObstaclesBicycle",
        perceptionUnknownMovable: "showObstaclesUnknownMovable",
        perceptionUnknownUnmovable: "showObstaclesUnknownUnmovable",
        perceptionUnknown: "showObstaclesUnknown",
        perceptionVirtual: "showObstaclesVirtual",
        perceptionCipv: "showObstaclesCipv",
        perceptionVelocity: "showObstaclesVelocity",
        perceptionHeading: "showObstaclesHeading",
        perceptionId: "showObstaclesId",
        perceptionObstacleInfo: "showObstaclesInfo",
        perceptionLidarSensor: "showObstaclesLidarSensor",
        perceptionRadarSensor: "showObstaclesRadarSensor",
        perceptionCameraSensor: "showObstaclesCameraSensor",
        perceptionV2xInfo: "showObstaclesV2xInfo",
        showObstaclesPostFusionObject: "showObstaclesPostFusionObject",
        showObstaclesBevObject: "showObstaclesBevObject",
        showObstaclesPvFmNarrowObject: "showObstaclesPvFmNarrowObject",
        showObstaclesPvFmWideObject: "showObstaclesPvFmWideObject",
        showObstaclesPvLbPinholeObject: "showObstaclesPvLbPinholeObject",
        showObstaclesPvRbPinholeObject: "showObstaclesPvRbPinholeObject",
        showObstaclesPvFmFisheyeObject: "showObstaclesPvFmFisheyeObject",
        showObstaclesPvLmFisheyeObject: "showObstaclesPvLmFisheyeObject",
        showObstaclesPvRmFisheyeObject: "showObstaclesPvRmFisheyeObject",
        showObstaclesPvBmFisheyeObject: "showObstaclesPvBmFisheyeObject",
        showObstaclesBevPostObject: "showObstaclesBevPostObject",
        showObstaclesPvPostFmNarrowObject: "showObstaclesPvPostFmNarrowObject",
        showObstaclesPvPostFmWideObject: "showObstaclesPvPostFmWideObject",
        showObstaclesPvPostLbPinholeObject:
          "showObstaclesPvPostLbPinholeObject",
        showObstaclesPvPostRbPinholeObject:
          "showObstaclesPvPostRbPinholeObject",
        showObstaclesOccupancyObject: "showObstaclesOccupancyObject",
        positionGps: "showPositionGps",
        positionLocalization: "showPositionLocalization",
        virtualChassis: "showVirtualChassis",
        positionCloseLoop: "showPositionCloseLoop",
        positionShadow: "showPositionShadow",
        mapCrosswalk: "showMapCrosswalk",
        mapClearArea: "showMapClearArea",
        mapJunction: "showMapJunction",
        mapPncJunction: "showMapPncJunction",
        mapLane: "showMapLane",
        mapCenterLane: "showMapCenterLane",
        mapRoad: "showMapRoad",
        mapSignal: "showMapSignal",
        mapStopSign: "showMapStopSign",
        mapYield: "showMapYield",
        mapSpeedBump: "showMapSpeedBump",
        mapParkingSpace: "showMapParkingSpace",
        mapLaneId: "showMapLaneId",
      },
      customizedToggles: {},
      showTasks: true,
      showModuleController: false,
      showMenu: false,
      showRouteEditingBar: false,
      showPOI: false,
      showDataRecorder: false,
      showProfile: false,
      showPNCMonitor: false,
      showPredictionMonitor: false,
      showEfficientLaneMonitor: false,
      showVirtualCloseLoop: false,
      showCloseLoop: false,
      showDataCollectionMonitor: false,
      showFuelClient: false,
      enableSimControl: false,
      lockTaskPanel: false,
      showVideo: true,
      showVideo2: true,
      showVideo3: false,
      showVideo4: false,
      showVideo5: false,
      showVideo6: false,
      showVideo7: false,
      showModuleDelay: false,
      showSimpleMonitor: false,
      showMessageSize: false,
      showSpeedAcc: true,
      showDeltaTime: true,
      showTimeInterval: false,
      showControlPanel: true,
      showBevRight: true,
      showPredictionObject: true,
      showPerceptionObject: false,
      showPncObject: false,
      showPolygon: false,
      showFollowCar: true,
      showHighMap: true,
      showMapShoulder: true,
      showTopoTree: false,
      showRoadStructure: false,
      showVectorizedLane: false,
      showLaneMap: false,
      showPredictionPath: false,
      showCurbSet: false,
      showNaviTwoKm: false,
      showDimensionalCar: false,
      showConsoleTeleopMonitor: false,
      showCarTeleopMonitor: false,
      cameraAngle: "Orthographic",
      showDecisionMain: true,
      showDecisionObstacle: true,
      showPlanningTrajectory: true,
      showPlanningCar: false,
      showPlanningPath: true,
      showPlanningRSSInfo: false,
      showPlanningMultiPolicy: false,
      showRouting: false,
      showPredictionMajor: true,
      showVehicleFlowLines: false,
      showEfficientLane: false,
      showEfficientNavi: true,
      showCurbTag: true,
      showRoadStructureCurb: false,
      showPredictionMinor: true,
      showGaussianInfo: false,
      showPredictionPriority: false,
      showPredictionInteractiveTag: false,
      showPredictionDecision: true,
      showPointCloud: false,
      showPerceptionObjectTopic: false,
      showPerceptionTypeStaticUnkonwn: false,
      showPerceptionLaneMarker: false,
      showObstacleStatus: false,
      showGoalLaneInJunction: true,
      showAdcLocalizationQuality: false,
      showObstaclesVehicle: true,
      showObstaclesPedestrian: true,
      showObstaclesBicycle: true,
      showObstaclesUnknownMovable: true,
      showObstaclesUnknownUnmovable: true,
      showObstaclesUnknown: true,
      showObstaclesVirtual: false,
      showObstaclesCipv: true,
      showObstaclesVelocity: true,
      showObstaclesHeading: true,
      showObstaclesId: true,
      showObstaclesInfo: true,
      showObstaclesLidarSensor: false,
      showObstaclesRadarSensor: false,
      showObstaclesCameraSensor: false,
      showObstaclesV2xInfo: false,
      showObstaclesPostFusionObject: true,
      showObstaclesBevObject: false,
      showObstaclesPvFmNarrowObject: false,
      showObstaclesPvFmWideObject: false,
      showObstaclesPvLbPinholeObject: false,
      showObstaclesPvRbPinholeObject: false,
      showObstaclesPvFmFisheyeObject: false,
      showObstaclesPvLmFisheyeObject: false,
      showObstaclesPvRmFisheyeObject: false,
      showObstaclesPvBmFisheyeObject: false,
      showObstaclesBevPostObject: false,
      showObstaclesPvPostFmNarrowObject: false,
      showObstaclesPvPostFmWideObject: false,
      showObstaclesPvPostLbPinholeObject: false,
      showObstaclesPvPostRbPinholeObject: false,
      showObstaclesOccupancyObject: false,
      showPositionGps: false,
      showPositionLocalization: true,
      showVirtualChassis: false,
      showPositionCloseLoop: true,
      showPositionShadow: false,
      showMapCrosswalk: true,
      showMapClearArea: true,
      showMapJunction: false,
      showMapPncJunction: false,
      showMapLane: true,
      showMapCenterLane: false,
      showMapRoad: false,
      showMapSignal: true,
      showMapStopSign: true,
      showMapYield: true,
      showMapSpeedBump: true,
      showMapParkingSpace: true,
      showMapLaneId: false,
      showDefaultRoutingInput: false,
      showCycleNumberInput: false,
      selectPNCMonitorTab: 0,
      showPNCPlanningPanel: false,
      showPNCPlanningCore: true,
      showPNCPlanningBoundary: true,
      showPNCPlanningBuffer: false,
      showPNCControlPanel: false,
      showPlanningStatusPanel: true,
      showOperator: false,
      showSideBar: false,
      showTools: false,
      showTimestamp: true,
      cameraDraggable: false,
      showPncDebug: false,
      showLonBehavior: false,
      showSpeedHeuristic: true,
      showPlanningSTGraph: true,
      showPlanningVTGraph: true,
      showPlanningSpeed: true,
      showPlanningAcceleration: true,
      showPlanningTheta: true,
      showPlanningKappa: true,
      showPlanningKappaDerivative: true,
      showReferenceLineTheta: true,
      showReferenceLineKappa: true,
      showReferenceLineKappaDerivative: true,
      showControlTrajectory: true,
      showControlSpeed: true,
      showControlAcceleration: true,
      showControlCurvature: true,
      showControlStationError: true,
      showControlLateralError: true,
      showControlHeadingError: true,
      showLatencyGraph: true,
      showInteractColor: false,
      togglesToHide: {
        perceptionPointCloud: false,
        perceptionLaneMarker: false,
        planningCar: false,
      },
    },
    monitorWidth: 0,
    pane: { width: 745, height: 925 },
    main: { width: 745, height: 925 },
    scene: { width: 745, height: 925 },
    navigation: { width: 223.5, height: 300, size: "default" },
  },
  newDisengagementReminder: false,
  offlineViewErrorMsg: null,
};

module.exports = store